version: '3.8'

services:
    challenge-charlie:
        container_name: app-dev
        image: app-dev
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        volumes:
            - ./src:/app/src
        ports:
            - 3000:3000
